across-protocol/across-token

contracts/AcceleratingDistributor.sol, test/AcceleratingDistributor.Admin.ts, test/AcceleratingDistributor.Events.ts
*H-01 Anyone can prevent stakers from getting their rewards*
The recoverErc20 function is meant to facilitate the recovery of any ERC20 tokens that maybe mistakenly sent to the AcceleratingDistributor contract. As this is a public function
with no modifiers, anyone can call this function to transfer an ERC20 token from the AcceleratingDistributor contract to the owner of AcceleratingDistributor . The
only ERC20 tokens that are explicitly disallowed from being recovered are stakedToken that have already been initialized in the system.
However, it is currently possible to recover the ERC20 rewardToken using the recoverErc20 function. Doing so would transfer some specified amount of rewardToken
from the AcceleratingDistributor contract to the contract's owner. This would, subsequently, …
=> fix h01: address issue in recoverErc20 function

contracts/AcceleratingDistributor.sol
L-03 Unhandled failures in token interactions
There are ERC20 transfer operations, executed over potentially untrusted ERC20 tokens, which are not correctly wrapped to ensure that they are always safe and behave as expected.
Specifically, for the transfer on line 177 of the AcceleratingDistributor contract, the current implementation does not handle a case where the call to transfer fails by returning
a false boolean value (rather than reverting the transaction).
For more predictable and consistent behavior, consider using the OpenZeppelin SafeERC20 library which is used for other transfers throughout the codebase, as it implements wrappers
around ERC20 operations that return false on failure.
added the use of `safeTransfer` to the one line on 177 where this was missing.
=> fix l03: address missing safeTransfer

contracts/AcceleratingDistributor.sol
*L-04 Unused inherited contracts*
The AcceleratingDistributor contract imports and inherits from the Pausable contract but does not use any of the inherited functionality.
Consider either using the inherited Pausable functionality or else not inheriting from the Pausable contract.
the `Pausable` contract was removed from the inherited path.
=> fix l03: removed unused contract

contracts/AcceleratingDistributor.sol, contracts/AcrossToken.sol
*N-01 Visibility unnecessarily permissive*
The mint and burn functions of the AcrossToken contract and enableStaking , stake , getCumulativeStaked , and getUserStake of the
AcceleratingDistributor contract are marked as public , while they could be marked as external .
Updated mentioned functions to `external`.
=> fix n01: updated function visibility

contracts/AcceleratingDistributor.sol
In the AcceleratingDistributor contract the rewardToken variable could be marked immutable given that is only ever set in the constructor.
If rewardToken is never meant to be modifiable, then consider marking it immutable to better signal intent and reduce gas consumption.
Recommendation done.
=> fix n05: mark immutable variables as immutable

contracts/AcceleratingDistributor.sol, test/AcceleratingDistributor.RewardAccumulation.ts
*N-07 Typographical errors*
The codebase contains the following typographical errors:
In AcceleratingDistributor.sol :
- On line 17 and line 89 pro-rate should be pro-rata .
- On line 126, after the end of the staking program ends is ungrammatical.
- On line 202, exists should be exits .
- On line 203, callers should be caller's .
- On line 228, the all information associated should be all the information associated .
Consider correcting these typos to improve the overall readability of the codebase.
All identified typos have been corrected.
=> fix n07: addressed typographical errors

contracts/AcceleratingDistributor.sol, test/AcceleratingDistributor.Events.ts
* L-01 Incomplete and unindexed events*
Throughout the codebase, events are used to signify when changes are made to the state of the system. However, all of the existing events lack indexed parameters. Some events are
missing parameters necessary to fully indicate how the state was modified during a call.
Events lacking indexed parameters include:
The TokenEnabledForStaking , RecoverErc20 , Stake , Unstake , GetReward ,
and Exit events in the AcceleratingDistributor contract.
Event emissions which do not fully track state changes include:
- The RecoverErc20 event does not emit the caller, which may be of interest to those interested in calls to the recoverErc20 function where the event is emitted.
- The Stake , Unstake , and Exit events are emitted when a user calls the stake , unstake , …
=> fix l01: addition event information

contracts/AcceleratingDistributor.sol, test/AcceleratingDistributor.Admin.ts, test/AcceleratingDistributor.Events.ts, test/AcceleratingDistributor.Fixture.ts, test/AcceleratingDistributor.RewardAccumulation.ts, test/AcceleratingDistributor.RewardTokenFlow.ts, test/AcceleratingDistributor.TimeEvolution.ts
*N-03 Misleading function names*
In the AcceleratingDistributor contract there are multiple functions, storage variables, and events that have misleading names. These could potentially confuse users and lead to
unintentional or unexpected consequences when interacting with the contract. For instance:
- The function name enableStaking implies that it can only be used to enable a staking token. However, the function can be used to enable or disable a staking token, and/or
modify the properties baseEmissionRate , maxMultiplier or secondsToMaxMultiplier . Consider renaming the function to configureStakingToken .
- The enableStaking function emits the event TokenEnabledForStaking . Consider renaming the event to better reflect the actual use case of the emitting function as
outlined in the …
=> fix n03: Address misleading function names

contracts/AcceleratingDistributor.sol
*N-04 Missing documentation details*
In the AcceleratingDistributor contract several parts of the documentation contain missing or misleading details. For instance:
- The functions getUserRewardMultiplier and baseRewardPerToken return ratios or multipliers represented by a uint256 value with a fixed precision of 18 decimals. However, the decimal precision used is not documented.
The contract-level documentation refers to a maxEmissionRate . However, the implementation uses a maxMultiplier which is multiplied with a baseEmissionRate instead.
- To increase the overall readability of the codebase and reduce potential confusion, consider clarifying the documentation and adding missing details where appropriate.
All recommendations have been implemented.
=> fix n04: N-04 Missing documentation details

contracts/AcceleratingDistributor.sol, test/AcceleratingDistributor.Admin.ts
﻿*The codebase generally lacks sufficient input validation.*
In the AcceleratingDistributor contract, the enableStaking function allows the
contract owner to configure several parameters associated with a stakedToken . Several of these parameters have no input checking. Specifically:
- The maxMultiplier parameter has no upper or lower bound.
- It should be restricted to being larger than the "base multiplier" of 1e18 , or else it can lead to users' staking rewards decreasing over time rather than increasing.
- It should also have an upper bound, because if it were to be set to some very large value it could cause the getUserRewardMultiplier function to revert on overflow. This
could, in turn, cause calls to the getOutstandingRewards and _updateReward functions to revert. This would …
=> fix m01: addition of more input validation

contracts/AcceleratingDistributor.sol, contracts/test/Testable.sol, test/AcceleratingDistributor.Fixture.ts
*N-06 Test code in production could have security implications*
As we have raised in prior audits (issue L12) test code in production code is less than ideal. We will not simply rehash our previously raised concerns and suggestions, but we do feel it
prudent to expound on some of the potential security implications of having test code in production in this particular case:
The AcceleratingDistributor contract inherits from the Testable contract. This facilitates modification of the getCurrentTime function's behavior during testing. This
inheritance is meant to be kept in production. This is considered safe because passing the zero address for the parameter _timer during deployment will disable the testing module and
return block.timestamp instead. 
The contract logic ensures that all …
=> fix n06: remove test code in production version

contracts/AcceleratingDistributor.sol, contracts/AcrossToken.sol, test/AcceleratingDistributor.Admin.ts
*N-02 System is incompatible with non-standard ERC20 tokens*
Currently, the system is incompatible with non-standard ERC20 tokens and enabling such tokens for staking could lead to loss of funds in the following ways:
1. The system's internal accounting mechanism does not currently support tokens that can charge fees on transfers, such as Tether (USDT) (the most widely known asset with this
feature). This means that such tokens' transfer and transferFrom functions could potentially fail to increase the recipient's balance by the amount that is actually transferred.
If AcceleratingDistributor allows staking of tokens charging such transfer fees, then stakers would receive more rewards than intended.
2. The recoverErc20 function is currently callable by any address. This could be …
=> fix n02: updated comments around non-standard ERC20 tokens

contracts/AcceleratingDistributor.sol
`baseRewardPerToken` returns surprising precision for non 18 decimal `stakedTokens`
=> improve: Add comments about baseRewardPerToken to AcceleratingDistributor

package.json, test/ClaimAndStake.ts, yarn.lock
MerkleTree currently imported in this repo is out of date with latest in @uma/common and @across-protocol/contracts-v2
=> improve: Update MerkleTree import to be consistent with contracts-v2

test/AcceleratingDistributor.Admin.ts
A pending change will make the AD contract on staking methods when amount=0.
This breaks a few tests, so prepare updates for those in advance of introducing the
change.
=> improve: Prepare AD Admin test for updates

contracts/AcceleratingDistributor.sol, test/AcceleratingDistributor.Admin.ts
The OZ December 2022 audit identified a lack of input validation on the following functions:
- stakeFor() (missing validation of beneficiary address).
- unstake()  (missing validation on the amount input).
- _stake()   (missing validation on the amount input).
This change applies input validation to the externally-accessible functions.
=> fix: [L-02] Lack of input validation

contracts/AcceleratingDistributor.sol
Add documentation for:
- UserDeposit and StakingToken structs.
- getAverageDepositTimePostDeposit()
- getCurrentTime()
- _stake()
Update documentation for:
- Overall contract.
- recoverToken()
- stake()
- stakeFor()
- unstake()
- withdrawReward()
- exit()
- _updateReward()
Note that some of the docstrings relating to failure scenarios are predicated on the following PR being merged: https://github.com/across-protocol/across-token/pull/47
=> fix: [L-03] Add missing documentation

contracts/AcceleratingDistributor.sol, test/AcceleratingDistributor.Admin.ts
Enforce a minimum 1x multiplier to mitigate the potential for underflow in getUserRewardMultiplier(). There's currently no known use case for a maxMultiplier of less than 1x.
=> fix: [L-04] Clamp maxMultiplier lower bound to 1e18

contracts/AcceleratingDistributor.sol, test/AcceleratingDistributor.Events.ts
The userRewardsOutstanding value is always set to 0 when emitted, so remove it.
=> improve: [N-01] Remove redundant event parameter

contracts/AcceleratingDistributor.sol
Per an OZ finding, the recoverToken() function specifically checks for whether the token has been initialized; not whether it is currently enabled via staking configuration.
Note that an additional comment regarding the maxMultiplier used in tests was provided. This is currently _not_ implemented, because the current maxMultiplier of 3 represents current Across LP staking policy, rather than the technical constraints of the underlying contract.
=> fix: [N-02] Misleading documentation

contracts/AcceleratingDistributor.sol
=> fix: [N-04] Minor typographical errors

contracts/AcceleratingDistributor.sol, test/AcceleratingDistributor.Admin.ts
The configureStakingToken function in the AcceleratingDistributor contract
contains hard-coded upper limits that ensure maxMultiplier is set below 1e36 and
baseEmissionRate is set below 1e27 . However, these limits are many orders of magnitude
above the intended operating parameters for the contract.
According to the Across documentation for rewards locking, the value of maxMultiplier
should never exceed 3e18 for the initial reward locking program; 1e36 is many orders of
magnitude larger.
The rewards locking documentation also states that the initial token supply for rewards is
75,000,000 ACX tokens. This equates to 7.5e25 wei, but the upper limit of 1e27 on
baseEmissionRate allows a token emission rate per second that is two orders of magnitude
higher than the total supply to be emitted. …
=> fix: [L01] Dangerous maximum values for reward calculations

contracts/AcceleratingDistributor.sol
Relating to the M-01 finding from OpenZeppelin, the proposal is to document the implications of performing various configuration updates to a pre-existing configured staking token.
=> improve(AD): [M-01] Clarify staking config change implications

contracts/AcceleratingDistributor.sol
These should have been handled as part of the following commit, but were not:
5254dec7e853ff978142272289005b741cbe04cc
=> fix: Correct residual typographical errors

contracts/AcceleratingDistributor.sol
These were erroneously removed in the following commit:
be635c47f7860bc8759aac3e6152e4c6da7221d3.
=> fix: Reinstate docstrings

README.md, contracts/AcceleratingDistributor.sol
Refactors withdrawRewards() and unstake() to call internal methods _withdrawRewards() and _unstake() so that exit() only calls _updateRewards() once
=> refactor(accelerating-distributor): Remove redundant _updateRewards from exit()
